### ISSUE TITLE
Windows built-in support

### ISSUE THREAD

**Issue by Slion** [springcomp/optimized-azerty-win#114] opened 2023-02-04 06:18 UTC
According to [kbdlayout.info](http://kbdlayout.info) old AZERTY is now legacy and new one is standard, though legacy is still the default. Yet on Windows 11 I still can't find built-in support for the new layout.

**Comment by springcomp** [comment] 2023-02-08 12:57
Thanks for the information. That is very interesting.
Can you check your Windows version?

I’d like to investigate this and document that Windows now supports AZERTY-NF natively.
Although, the version in this repository is still more powerful 😉.

**Comment by Slion** [comment] 2023-02-08 14:27
I check on the latest Windows 11 and the guy at kbdlayout.info mentioned his stuff is from Windows 10.

**Comment by springcomp** [comment] 2023-02-08 15:18
The kbdlayout mentions version `25272.1000` which is very very recent.

I have not seen this version in the wild yet.

**Comment by miloush** [comment] 2023-02-08 16:49
This should be available in public Windows insider builds. Thanks for the "Windows 10" note, I should update that. :)

**Comment by Slion** [comment] 2023-02-08 16:57
@miloush is the guy running kbdlayout.info. Thanks again for helping us out with this.

Would it be possible to generate such [XML file](http://kbdlayout.info/kbdfrna/download/xml) for the layout that @springcomp is providing? @springcomp does your software include such a keyboard DLL that @miloush is using to generate that XML file?

**Comment by miloush** [comment] 2023-02-08 17:46
The DLL file is the result of building the layout. I believe I can generate XML file from the KLC files too. Have you tried them here? http://kbdlayout.info/viewer might be able to give you the XML file from KLC.

**Comment by springcomp** [comment] 2023-02-08 23:14
Analyzing the differences one can observe that:

- Both implementations have different positions for virtual keys OEM1, OEM2, OEM3, OEM4 and OEM7
 
> I’m not sure if there is _a correct_ way. Nor do I understand the full impacts.
   
- Windows implementation is using different code points for <kbd>AltrGr</kbd>+<kbd><</kbd> and <kbd>AltrGr</kbd>+ <kbd>Shift</kbd><kbd>+</kbd>:
    - Windows outputs `⩽` **U+2A7D LESS-THAN OR SLANTED EQUAL TO** whereas
    - This implementation outputs `≤` **U+2264 LESS-THAN OR EQUAL TO**.
    - Windows outputs `⩾` **U+2A7E GREATER-THAN OR SLANTED EQUAL TO**  whereas
    - This implementation outputs `≥` **U+2265 GREATER-THAN OR EQUAL TO**.

> I believe the Windows implementation to actually [be incorrectly](https://github.com/springcomp/optimized-azerty-win/issues/79) interpreting the standard.

_This post will be updated as further analysis is performed and shared here_

**Comment by Slion** [comment] 2023-02-10 18:02
AltGr+M does infinite symbol on the Windows layout but yours does not have that it seems. Is that missing or is it not in the specs . I rather like it. Can we have it? 😁

**Comment by springcomp** [comment] 2023-02-10 20:49
@Slion the layout is definitely designed to output `∞` using <kbd>AltGr</kbd>+<kbd>m</kbd> (lowercase m).
I use this layout daily on at least three computers and happen to use this symbol a lot as well. It definitely works there.

Please, can you double-check and tell me [which version of the layout](https://github.com/springcomp/optimized-azerty-win/wiki/FAQ#which-version) you have?

**Comment by Slion** [comment] 2023-02-10 23:16
v1.7.0.0 on Windows 11. Tried both the digits and the other layout. That's odd.

**Comment by springcomp** [comment] 2023-02-11 08:35
@Slion Would you be able to run [the compliance tests](https://github.com/springcomp/optimized-azerty-win-compliance) on your machine ?

**Comment by Slion** [comment] 2023-02-13 10:22
I did not get around running those tests yet. However I was just trying it out on a Windows 10 machine I also you regularly it works great there. I'm guessing this is a Windows 11 issue.

**Comment by jbrianceau** [comment] 2023-02-13 10:58
> The kbdlayout mentions version `10.0.25272.1000` which is very very recent.
> 
> I have not seen this version in the wild yet.

It has been officially released in Windows 11 Insider Preview Build 25247 that was announced [here](https://blogs.windows.com/windows-insider/2022/11/18/announcing-windows-11-insider-preview-build-25247/), in the `[Input]` section:

> We are including two new keyboard layouts in this flight. These keyboards implement the two new French keyboard layout standards (AZERTY and BÉPO). The new layouts are designed to allow the user to type all the required characters of the French language. They also include support for all the Latin-based languages of the European Union as well as Greek letters and a large variety of scientific, mathematical, and financial symbols. To enable one of these layouts, go to Settings > Time & language > Language & region and select Language options under the ellipsis for the language you would like to use this keyboard with. On the Options page, select “Add a keyboard” and look for the new keyboard layouts “French (Standard, AZERTY)” or “French (Standard, BÉPO)”. The previous AZERTY layout now displays as (Legacy, AZERTY).

**Comment by Slion** [comment] 2023-02-13 11:13
That's fantastic news! Hopefully Android will follow and hardware manufacturers too. It took them only 4 years since the publication to implement it. I'm impressed 😁

**Comment by springcomp** [comment] 2023-02-13 17:19
@jbrianceau that’s indeed great news.

For the sake of my sanity, @jbrianceau  could you please 🙏 double-check [this issue](https://github.com/springcomp/optimized-azerty-win/issues/114#issuecomment-1423362269) above with regards to greater-than and less-than signs ?

As a hobbyist I could never actually check the official standard document – although [I have sources](https://github.com/springcomp/optimized-azerty-win/issues/79#issuecomment-559606830) that did, indeed, check the official document. My understanding is that those two characters are incorrect in the Windows layout 🤔.

**Comment by jbrianceau** [comment] 2023-02-14 08:45
I have access to a printed version of the NF Z 71-300 French norm from April 2019.
Here's what I can tell:
- page 15, §6.2.3 (Signes numériques et scientifiques) states the requirement that digits and main symbols that are needed for maths, scientific or technical purpose must be handled
- page 16, table 8 (Symboles) lists those main symbols and is explicit about the unicode value that has to be used

| Code Unicode | Glyphe | Nom |
|-|-|-|
| U+0023 | # | Croisillon |
| ... | ... | ... |
| U+2264 | ≤ | Inférieur ou égal |
| U+2265 | ≥ | Supérieur ou égal |
| ... | ... | ... |

However, when looking at the detailed implementation of AZERTY layout later in the specs:
- page 27, in figure A.1 (Carte complète de la disposition AZERTY), symbols ⩽ and ⩾ are used
- page 29, table A.1 (Points de codage de la disposition AZERTY) is explicit about it:

| Touche | Goupe 1 / Niveau 1 | Groupe 1 / Niveau 2 | Groupe 2 / Niveau 1 | Groupe 2 / Niveau 2 |
|-|-|-|-|-|
| ... | ... | ... | ... | ... |
| B00 | U+003C < | U+003E > | U+2A7D ⩽ | U+2A7E ⩾ |
| ... | ... | ... | ... | ... |

Same for the BÉPO layout:
- page 40, in figure B.1 (Carte complète de la disposition BÉPO), symbols ⩽ and ⩾ are used
- page 41, table B.1 (Points de codage de la disposition BÉPO) is explicit about it:

| Touche | Goupe 1 / Niveau 1 | Groupe 1 / Niveau 2 | Groupe 2 / Niveau 1 | Groupe 2 / Niveau 2 |
|-|-|-|-|-|
| ... | ... | ... | ... | ... |
| E04 | U+0028 ( | U+0034 4 | U+005B [ | U+2A7D ⩽ |
| E05 | U+0029 ) | U+0035 5 | U+005D ] | U+2A7E ⩾ |
| ... | ... | ... | ... | ... |

- page 51, table B.6 (Caractères saisis par la touche morte ∞) mention the possibility to output ≤ and ≥ using a dead key

| Touche | Symbole gravé | Goupe 1 / Niveau 1 | Groupe 1 / Niveau 2 | Groupe 2 / Niveau 1 | Groupe 2 / Niveau 2 |
|-|-|-|-|-|-|
| E04 | ( |  |  |  | U+2264 ≤ |
| E05 | ) |  |  |  | U+2265 ≥ |
| ... | ... | ... | ... | ... | ... |


So there's definitely a discrepancy here between the table 8 of the beginning and the rest of the document, but my understanding is that the spec intent is ⩽ and ⩾ in the AZERTY layout.

Also, on a more personal note, I remember math teachers writing ⩽ and ⩾ on the board, but I don't remember them writing ≤ and ≥ when I was a student. This is definitely not a proof for the spec's intent, but this makes me think that this could be common usage in French.

**Comment by springcomp** [comment] 2023-02-14 08:50
@jbrianceau 
> I have access to a printed version of the NF Z 71-300 French norm from April 2019. Here's what I can tell […]

Thank you **so much** for digging into this for me.
I think we will agree to disagree on the output 😉 as there could be differing interpretations.

On another note, you may be interested to report the missing support for **U+2003 EM SPACE** in the Windows implementation.

**Comment by jbrianceau** [comment] 2023-02-14 10:02
> On another note, you may be interested to report the missing support for **U+2003 EM SPACE** in the Windows implementation.

The "espace cadratin" (U+2003) is part of table 12 (Espaces typographiques) page 20, but it doesn't seem to be referenced anywhere in the AZERTY layout described in appendix A (I wish I had an electronic version of the spec and not a paper one 😅).

It is however part of the BÉPO layout described in appendix B:
- page 49, table B.5 (Caractères saisis par la touche morte ß)

| Touche | Symbole gravé | Goupe 1 / Niveau 1 | Groupe 1 / Niveau 2 | Groupe 2 / Niveau 1 | Groupe 2 / Niveau 2 |
|-|-|-|-|-|-|
| ... | ... | ... | ... | ... | ... |
| A03 | | | U+2003 (Espace cadratin) | | |

- page 50 in figure B.4 (Carte des caractères latins et des ponctuations additionnels)

Where should the "espace cadratin" be located in the AZERTY layout?

**Comment by miloush** [comment] 2023-02-14 10:09
It sounds like §6.2.3 says "your keyboard has to output these" but doesn't mandate on which keys. So you can still have the layouts in the appendices and meet §6.2.3 which is what the Windows layout is doing

**Comment by springcomp** [comment] 2023-02-14 10:10
> Where should the "espace cadratin" be located in the AZERTY layout?

My understanding was that <kbd>Ctrl</kbd>+<kbd>Space</kbd> should emit **U+2003 EM SPACE**.
But you definitely have a more authoritative source than I ever hoped to lay my hands on while authoring the version in this repository.

**Comment by Slion** [comment] 2023-02-14 11:51
If we are voting on the "equal to" characters to use I'd rather have the slanted version cause they are a more accurate representation of handwriting. However for smaller font size the non-slanted version are easier to read for my aging eyes. So I also understand the argument about using ≤≥.

Historically I'm guessing the slanted variants only came later as they would have been unreadable on older low res displays.

**Comment by miloush** [comment] 2023-02-14 11:57
> Historically I'm guessing the slanted variants only came later as they would have been unreadable on older low res displays.

The slanted variant is from Unicode 3.2 (2002) while the normal variant is there pretty much from the beginning.

Only 3 fonts on Windows currently support the slanted characters: Cambria, Cambria Math and Segoe UI Symbol, while pretty much any font supports the normal one.

**Comment by springcomp** [comment] 2023-02-14 12:59
> If we are voting on the "equal to" characters […]

I’m contacting members of the AFNOR design team to have a feedback.
The fact that the text has a conflict is not something I’m comfortable with.

That said, I seem to remember that the document starts with _informative_ text and concludes with _normative_ text.
I seem to remember that, indeed, the normative text specifies the slanted variants of the glyphs.

**Comment by tgrouas** [comment] 2023-02-14 14:58
> I’m contacting members of the AFNOR design team to have a feedback.
> The fact that the text has a conflict is not something I’m comfortable with.

Hi, I was involved in the french keyboard layout standard comitee.

You point out something that definitely is an issue in the standard. I can fully confirm that the consensus in that comitee was to use U+2A7D ⩽ and U+2A7E ⩾ because that is the symbol most generally used in France while writting with hand, especially in school, high school and university. The character was added in the azerty layout and bepo layout annexes, but the older U+2264 ≤ and U+2265 ≥ where kept by mistake on the common, general list of mandatory characters for both layouts.

Consequences if you want to have a 100% compliant driver:

- U+2264 ≤ and U+2265 ≥ are both listed as mandatory to be included in the layout [§6.2.3], but can be added anywhere there is a free spot on the layout, its position is up to the driver manufacturer/developper
- U+2A7D ⩽ and U+2A7E ⩾ are listed as mandatory to have on the Alt-Gr B00 Key and  Alt-Gr Shift B00 for an azerty compliant keyboard
- Both are mandatory in the standard BEPO layout

It may be possible to correct this mistake in a future revision of the standard, either by :
- replacing U+2264 ≤ and U+2265 ≥  by U+2A7D ⩽ and U+2A7E ⩾ in the general, common list of mandatory symbols to provide;
- adding U+2264 ≤ and U+2265 ≥ on a free spot in the azerty annex requirements and U+2A7D ⩽ and U+2A7E ⩾ in the common general list of required symbols to provide.

Option n°2 definitely looks like a more compatible and safer update.

Other minor improvements could also be included such as the obligation to provide mathematical symbols such as +, -  as index or exponent when using the related dead keys in the azerty layout.

Hope this helps,

Best,

Thibault

**Comment by springcomp** [comment] 2023-02-14 15:27
> Hi, I was involved in the french keyboard layout standard comitee.

Amen 🤷‍♂️.

And thank you **so so much** for taking the time providing such a complete and insightful answer.

**Comment by tgrouas** [comment] 2023-02-14 15:31
> And thank you **so so much** for taking the time providing such a complete and insightful answer.

Well, thanks to you, and to everybody else contributing to this wonderful and awesome driver that on top of being compliant to the standard is also a joy to use !

**Comment by Slion** [comment] 2023-02-15 08:31
> The slanted variant is from Unicode 3.2 (2002) while the normal variant is there pretty much from the beginning.

Thanks for looking this up for me 😁

> Only 3 fonts on Windows currently support the slanted characters: Cambria, Cambria Math and Segoe UI Symbol, while pretty much any font supports the normal one.

That would be an issue as having a character that won't render on the your keyboard is not very helpful. However in practice it seems to render correctly in most places I tried on Windows 10.

Works in:
* Notepad
* Vivaldi search field
* Word – seems to force Cambria Math for that one character
* Android Studio

Does not work in:
* TortoiseGit commit message – you can change the font in the settings but not to one that supports it apparently

**Comment by miloush** [comment] 2023-02-15 09:21
> However in practice it seems to render correctly in most places I tried on Windows 10.

That is because of font fallback.

My main concern with this standardization decision would be if Unicode perceives these two characters as having different identities, i.e. having different meaning in some fields of mathematics, and the standard uses the slanted one to represent the normal one because its visual similarity of handwriting in the area. Users will suddenly start creating documents with the slanted characters that did not exist before and would not exist otherwise.

**Comment by springcomp** [comment] 2023-02-15 12:52
> My main concern with this standardization decision would be [users suddenly being able to] start creating documents with the slanted characters that did not exist before and would not exist otherwise.

On one hand I agree this is a concern.
On the other, my intent with this project is to be as much compliant as is possible.

Therefore, I’m inclined to fix this implementation and emit the standardized – slanted – versions, therefore agreeing with the interpretation made by the upcoming Windows implementation.

- <kbd>AltGr</kbd>+<kbd><</kbd> would _then_ emit the standardized `⩽` **U+2A7DLESS-THAN OR SLANTED EQUAL TO**.
- <kbd>AltGr</kbd>+<kbd>Shift</kbd>, <kbd>></kbd> would _then_ emit the standardized `⩽` **U+2A7DLESS-THAN OR SLANTED EQUAL TO**.

At the same time, as @tgrouas [suggested](https://github.com/springcomp/optimized-azerty-win/issues/114#issuecomment-1429881819), I think it would be worthwhile to keed support for those characters. I was thinking they could be moved the _European Characters_ layer with the following key combinations:

- <kbd>AltGr</kbd>+<kbd>Eu</kbd>, <kbd><</kbd> would emit the current `≤` **U+2264 LESS-THAN OR EQUAL TO**.
- <kbd>AltGr</kbd>+<kbd>Eu</kbd>, <kbd>AltGr</kbd>+<kbd>Shift</kbd>+<kbd>></kbd> would emit the current `≥` **U+2265 GREATER-THAN OR EQUAL TO**.

What do you think?

**Comment by Slion** [comment] 2023-02-15 13:12
I would rather have them in the Greek layers cause they are more related to math than to European characters. The monetary layer would also make more sense than the Eu layer IMHO.

**Comment by springcomp** [comment] 2023-02-15 14:05
> I would rather have them in the Greek layers cause they are more related to math than to European characters. The monetary layer would also make more sense than the Eu layer IMHO.

Good point. I actually was torn having the same thought.
@tgrouas would you have any thoughts on this?

**Comment by tgrouas** [comment] 2023-02-15 14:51
> @tgrouas would you have any thoughts on this?

yes, indeed. I was thinking first to the Eu character set and here is why :

- U+2264 and U+2265 are definitely not monetary symbols and I see absolutely no logical reason to include them on this set ;
- U+2264 and U+2265 are definitely not greek letters too. While these letters can find a lot of use for scientific purposes, they also can be used for all sorts of things, most common of them being writting greek names or titles in multilingual documents as they should be easily. Also. this character set only provide letters, no scientific symbols, so for me this makes the possibility to include U+2264 and U+2265 there not really logical
- U+2264 and U+2265 are commonly used in other european regions, mainly english speaking or german based languages. it makes sense to me to provide a more international way of writting this symbol through the Eu dead key character set, as you proposed.

Maybe there can be better solutions but I feel this one is at least consistent with the aim of the additional character sets in the standard layout, while not being optimal from an ergonomy point of view.

**Comment by springcomp** [comment] 2023-02-15 14:55
> yes, indeed. I was thinking first to the Eu character set and here is why […]

Thanks for the detailed reasoning.

**Comment by springcomp** [comment] 2023-02-16 14:38
Dear all ! @jbrianceau @Slion @tgrouas @miloush.

I’m proud to announce [Release 1.8.0.0](https://github.com/springcomp/optimized-azerty-win/releases/tag/v1.8.0.0) which brings all the changes discussed in this issue.

**Closed** 2023-02-16 14:38 UTC

**Comment by Slion** [comment] 2023-02-16 15:16
Windows 11 is preventing me to use the downloaded zip fie saying virus detected. Not even sure how to work around that.

**Comment by springcomp** [comment] 2023-02-16 15:28
> Windows 11 is preventing me to use the downloaded zip fie saying virus detected. Not even sure how to work around that.

Good point.
I need to understand how to sign the installer unfortunately.

I’m pretty sure there is a dropdown or small font link that allows you to bypass the SmartScreen filter.
Maybe clicking on `more information` and [revealing new options](https://github.com/springcomp/optimized-azerty-win/issues/94) ?

**Comment by springcomp** [comment] 2023-02-16 16:43
> I did try the MSI, looks like it ran but it did not update my layout. I'm guessing I need to uninstall the older version first.

Yes, please, [consult the FAQ](https://github.com/springcomp/optimized-azerty-win/wiki/FAQ#upgrade) for upgrading.

**Comment by Slion** [comment] 2023-02-16 17:47
> Still my infinite symbol is not working but I'm assuming some software is stealing the key somehow… I'm just not sure which one it could.

Got it, it was that Nvidia overlay.

**Comment by Slion** [comment] 2023-02-17 08:58
I would add Nvidia Shadow Play and Dell Display Manager to that wiki page. Can you give me edit rights to the wiki somehow? Maybe by making me a Collaborator on the project.

**Comment by springcomp** [comment] 2023-02-17 09:11
> I would add Nvidia Shadow Play and Dell Display Manager to that wiki page. Can you give me edit rights to the wiki somehow? Maybe by making me a Collaborator on the project.

Thanks a lot for proposing.
Are you familiar with git and _pull requests_ ?
In that case, please fork the [Wiki](https://github.com/springcomp/optimized-azerty-win-wiki) repository and submit your changes as a _pull request_

**Comment by Slion** [comment] 2023-02-17 09:25
Yeah I can do git but I'm too lazy to bother with that process for a couple of edits on a wiki page 😁 that's why I was suggesting direct edit. I guess I could just open an issue with the suggested additions so that you can just copy and paste it in the wiki.

**Comment by springcomp** [comment] 2023-02-17 09:32
> Yeah I can do git but I'm too lazy to bother with that process for a couple of edits on a wiki page 😁 that's why I was suggesting direct edit. I guess I could just open an issue with the suggested additions so that you can just copy and paste it in the wiki.

OK let me give you write access to the Wiki 🙄

**Comment by tgrouas** [comment] 2023-03-07 17:10
Thank you for the bug report. EM SPACE will likely be included in the Eu layer as suggested in the next revision of the standard due this year. Regarding currency sign, it will indeed be moved from erroneous AltGr E to AltGr F in the currency layer to make its input easy with a double tap. Best,

**Comment by springcomp** [comment] 2023-03-07 18:46
> Thank you for the bug report. EM SPACE will likely be included in the Eu layer as suggested in the next revision of the standard due this year.

Thanks. By any chance, do you know what would be the most likely candidate position?

> Regarding currency sign, it will indeed be moved from erroneous AltGr E to AltGr F in the currency layer to make its input easy with a double tap. Best,

Fortunately, the layout already support the standard position. I tried to _also_ support the more arcane position as well. That lead me to create a special dead-key for the <kbd>AltGr</kbd>+<kbd>Shift</kbd>+<kbd>E</kbd> as you rightly pointed out.

**Comment by tgrouas** [comment] 2023-03-07 20:08
> Thanks. By any chance, do you know what would be the most likely candidate position?

AltGr+Eu; AltGr+Space.

With a double check first to be sure that AltGr+Eu; Space is not technically possible as is it much better from an ergonomy point of view.

Best.

**Comment by dan-jac** [comment] 2023-03-08 09:59
> AltGr+Eu; AltGr+Space.
> With a double check first to be sure that AltGr+Eu; Space is not technically possible as is it much better from an ergonomy point of view.

From a _strictly technical_ perspective, AltGr+Eu, Space _is_ possible on Windows. But this would be a _very_ bad idea.

Doing this would violate the normal behaviour that you can always press space following any dead key to type the dead key character itself. This behaviour is currently applied to all dead keys across _all_ Windows' keyboard layouts, including both new layouts included in this _norme_. I don't think we should violate this rule just for _espace cadratin_.

With this in mind, I would think to advocate for placing the character on AltGr+Eu, AltGr+Space.

----

While we're on the subject of revisions to the _norme_ and the Eu dead key...

(Aside from workarounds to errata within the _norme_), That "Eu" dead key is the only area in which the Windows implementation of the layout is forced to deviate from the requirements of the _norme_ due to technical constraints of the Windows platform.

Those constraints are:
* A keystroke cannot *both* produce multiple characters *and* be a dead key. (Either *one* of these is possible.)
* Chaining multiple dead keys in the manner required to support diacritics on the ſ (LATIN LONG LETTER SMALL S) character is not possible.
(Note that chaining dead keys in the manner required by BÉPO is fully supported without issue.)

Both the Windows implementation and the implementation in this GitHub project have elected to work around these constraints in _exactly_ the same way – make ſ the dead key character instead of Eu. This allows diacritics to be placed on it directly, with fewer keystrokes, and it gives us *something* to place on the dead key instead of the impossible "Eu".

As an aside, there's a mistake in the _norme_ here where it says that the AZERTY layout does not involve combinations of dead keys:
![image](https://user-images.githubusercontent.com/50617707/223681080-7af6da55-8147-4d01-a7fe-248334632bca.png)

It appears as if this dead key poses a problem for Linux too. In my testing of Ubuntu 22.04 and 22.10, I found that the new AZERTY layout *is* included but the Eu dead key is absent _entirely_. All other features specified in the _norme_ are included, so my guess is that the omission of this dead key (without any workarounds) is due to technical constraints.

So for a future revision of the _norme_, I would propose that a different dead key character should be selected for the "Eu" dead key. It would obviously be very convenient for us all if that character were to be ſ. 😉

**Comment by miloush** [comment] 2023-03-08 10:05
Careful with the AlGr+Space. On it's own it invokes the system menu. When your keyboard does not have AltGr and you are forced to use Ctr+Alt instead, Ctrl+Alt+Space starts a voice reading in Word, even when in the middle of dead composition.

**Comment by miloush** [comment] 2023-03-08 10:09
In Visual Studio, it inserts U+200B ZWS

**Comment by dan-jac** [comment] 2023-03-08 10:14
> Careful with the AlGr+Space. On its own it invokes the system menu. When your keyboard does not have AltGr and you are forced to use Ctr+Alt instead, Ctrl+Alt+Space starts a voice reading in Word, even when in the middle of dead composition.

It is true that Ctrl+Alt+ all kinds of characters is a shortcut for many things, especially in Word. E.g. Ctrl+Alt+F is a shortcut for jumping to edit the page's footer. But this isn't a problem when you've got an AltGr key; AltGr+F correctly works as the monetary symbols dead key, without invoking the footer.

So to conclude, I think we just have to accept that if you've got a keyboard that for some reason lacks the right Alt key (which is mapped to AltGr in this layout), you're not going to be able to fully use the keyboard layout.

I think this is fine; I don't think I've *ever* encountered a keyboard that lacks a right Alt key.

I've not had any problems with AltGr+Space. This is already mapped to non-breaking space in the base layer. Mapping this to something else (em space) in a dead key layer won't add any _additional_ risk.

**Comment by miloush** [comment] 2023-03-08 10:21
The other risk is the keyboard layout working as designed and thus breaking other applications. Probably not so much of concern during a dead composition though, that goes after the user.

**Comment by tgrouas** [comment] 2023-03-08 10:54
> So for a future revision of the _norme_, I would propose that a different dead key character should be selected for the "Eu" dead key. It would obviously be very convenient for us all if that character were to be ſ.

Thanks for this proposal. To make sure I understand it completely, that means two changes :
- replacing the Eu symbol by the ſ character on the keyboard design/labelling + name of deadkey in the norme
- moving ſ from AltGr-H;s to AltGr-H;h

Is that correct ?

Best,

**Comment by dan-jac** [comment] 2023-03-08 13:02
@tgrouas, I don't want to be in the position of dictating the contents of the _norme_ from outside of its committee. So allow me to differentiate between technical requirements vs. an example of a specific proposal that you _could_ adopt...

**A specific proposal** (which might be desirable if you wish to make minimal changes from the original 2019 edition of the _norme_)
* Replace "Eu" with "ſ" on base layer as dead key for access to "caractères européens additionnels" layer.
   *  Inherent in doing this, while following implementation conventions throughout the rest of this layout, would be to *also* place "ſ" on the AltGr+H of the "caractères européens additionnels" layer. This is to ensure a double-tap of AltGr+H produces the dead key character, as is the case with all other dead keys. 
Thus, as a minimum, there would be two ways to type "ſ":
1. AltGr+H, Space
2. AltGr+H, AltGr+H

The Windows implementation already works this way, as this was the best workaround I could come up with to come as close as possible to the _norme_.

This proposal does not *necessarily* involve changing/moving/deleting other instances of "ſ" on the "caractères européens additionnels" layer. "ſ" is currently also housed on S, as per the requirements of the _norme_, in the Windows implementation.

This proposal has the benefit of being as close as possible to the original 2019 edition of the _norme_. However, the symbol "ſ" may not be as good as "Eu" at signifying to users that there's a layer full of "additional European characters". So I'm happy to let the committee recommend a different (single) character that might work better, if they prefer.

**Generalised technical requirements on Windows**
1. Dead keys must be a single character only. 
   * So "Eu", which is two characters, can't be used as a dead key.
3. In a chain of dead keys, it's not possible for the first keystroke to modify the third (or later) keystroke. A dead key can only modify the keystroke immediately following it.
   * Thus, it's not possible to type a diacritic dead key, then press a dead key to access a layer, then press a character in that layer and add a diacritic to it. (This would be required to adhere strictly to the _norme_'s requirements for adding diacritics to "ſ".)
   * BÉPO's use of chained dead keys doesn't run into this problem, so there are no problems with implementing the BÉPO layout.

**Comment by springcomp** [comment] 2023-03-08 13:48
@tgrouas  @dan-jac @miloush 

Thank you all for your valuable feedback.

> * Replace "Eu" with "ſ" on base layer as dead key for access to "caractères européens additionnels" layer.

I would clearly distinguish between what is written / engraved in a physical key and what character / codepoint it outputs.
To me, the standard should not be too concerned with perceived technical limitations. In any case, it currently does not designate any dead key associated with a dangling <kbd>AltGr</kbd>+<kbd>Eu</kbd> sequence, which is fine in my opinion.

In my version of the layout <kbd>AltGr</kbd>+<kbd>Eu</kbd>, <kbd>Space</kbd> **does not** produce any character at all. I think this is a cleaner approach than emitting a non intuitive character, such as `ſ`. Thus, typing the LATIN LETTER LONG S still requires the full standardized <kbd>AltGr</kbd>+<kbd>Eu</kbd>, <kbd>s</kbd> sequence.
   
> 
> **Generalised technical requirements on Windows**
> 
> 1. Dead keys must be a single character only.

In fact, that’s technically not quite true. Windows itself is perfectly happy with chained dead keys. And [software do exist](http://www.kbdedit.com/manual/dead_chained.html) to implement layout with complex requirements such as these. The limitation is currently within the MSKLC designer software. On could use the WDK (Windows Development Kit) or distribute the layout with [KbdEdit](http://kbdedit.com/).

I actually worked with the author of that software when designing my implementation, and we made some changes to the designer software to support a special case, namely to be able to output CURRENCY SIGN using (what I thought was) the standard <kbd>AltGr</kbd>+<kbd>¤</kbd>, <kbd>AltGr</kbd>+<kbd>Shift</kbd>+<kbd>E</kbd> sequence that worked outside the box with MSKLC.

> 2. In a chain of dead keys, it's not possible for the first keystroke to modify the third (or later) keystroke. A dead key can only modify the keystroke immediately following it.
>    
>    * Thus, it's not possible to type a diacritic dead key, then press a dead key to access a layer, then press a character in that layer and add a diacritic to it. (This would be required to adhere strictly to the _norme_'s requirements for adding diacritics to "ſ".)

@tgrouas Interesting. Wouldn’t it be possible to create additional "virtual layers" on top of the three mandated `¤`, `µ` and `Eu` layers? Each diacritical being an entry into a new virtual layer. I can easily imagine:

- <kbd>AltGr</kbd>+<kbd>Eu</kbd>, extended European characters layer.
-  <kbd>AltGr</kbd>+<kbd>◌/</kbd>, <kbd>AltGr</kbd>+<kbd>Eu</kbd>, extended short solidus overlayed characters layer.
-  <kbd>AltGr</kbd>+<kbd>◌˙</kbd>, <kbd>AltGr</kbd>+<kbd>Eu</kbd>, extended dotted above characters layer
- etc.

In the end, for simplicity reasons, I chose to design the first version of the layout using MSKLC as it supported unattended continuous deployment process here in GitHub and KbdEdit’s author did not want to allow his software to be used in an unattended manner. But I may revisit this in the future if that’s necessary.

**Comment by dan-jac** [comment] 2023-03-08 14:41
>In fact, that’s technically not quite true. Windows itself is perfectly happy with chained dead keys. And [software do exist](http://www.kbdedit.com/manual/dead_chained.html) to implement layout with complex requirements such as these. The limitation is currently within the MSKLC designer software. On could use the WDK (Windows Development Kit) or distribute the layout with [KbdEdit](http://kbdedit.com/).

It's true that the Windows limitations I've outlined are specific to the Windows OS build process (and also to the closely-related MSKLC).

Indeed, keyboard layouts in Windows are technically drivers, and it's possible to author a custom driver to do *anything* you might want.

However… Windows has an established system for authoring and building keyboard layouts, and for integrating these into the OS alongside components like touch keyboards, etc.

Overcoming those current limitations would require changes to that *entire* system. That would be a complex, high-risk, costly piece of work.

So for layouts that are going to be included with Windows, the limitations I've specified remain true. However, third-party layouts built with third-party authoring tools *could* do basically anything they want; these limitations need not necessarily apply to them.

> Wouldn’t it be possible to create additional "virtual layers" on top of the three mandated ¤, µ and Eu layers? Each diacritical being an entry into a new virtual layer. I can easily imagine:

I don't *think* this would work (at least not with the standard Windows OS and MSKLC keyboard driver building system).

Each dead key definition is defined *per character* in the .klc file. E.g.
```
DEADKEY 017F // caractères européens additionnels / additional European characters

0027	02bc	// ' -> '
0030	00ab	// 0 -> «
0037	203a	// 7 -> >
0038	2039	// 8 -> <

etc.
```

For this "virtual layers" concept to work, you'd end up needing to have a given DEADKEY character defined twice – once for the "normal" use case, and a second time for the special case where it follows one of the diacritics.

Having multiple DEADKEY definitions for the same DEADKEY character isn't supported.

**Comment by miloush** [comment] 2023-03-08 14:52
> Indeed, keyboard layouts in Windows are technically drivers, and it's possible to author a custom driver to do anything you might want.
> third-party layouts built with third-party authoring tools could do basically anything they want

I don't think that is accurate. While indeed the keyboard layouts can be authored in C and several of the kbdtool limitations (and bugs) can be overcome, you still need to stick to a passive KBDTABLES data structure that is loaded into memory and used by the input system, as far as I understand it, you cannot have arbitrary code executing, you would need an IME for that.

> Wouldn’t it be possible to create additional "virtual layers" on top of the three mandated ¤, µ and Eu layers?

I think that could work, but you would need substantial tooling support to help you, it would be a lot of work to do manually.

**Comment by springcomp** [comment] 2024-01-13 16:01
> @dan-jac thanks a lot for your very valuable feedback.
> I will [implement `EM SPACE`](#126) as you suggest and [fix the `CURRENCY SIGN`](#127) peculiarity of my layout.

@tgrouas @miloush I’m pleased to announce that I have [updated the layout](https://github.com/springcomp/optimized-azerty-win/releases/tag/v1.9.0.0) to support:

- EM SPACE (U+2003) typed using <kbd>AltGr</kbd>+<kbd>Eu</kbd>, <kbd>AltGr</kbd>+<kbd>Space</kbd>.
- EN SPACE (U+2002) typed using <kbd>AltGr</kbd>+<kbd>Eu</kbd>, <kbd>AltGr</kbd>+<kbd>Shift</kbd>+<kbd>Space</kbd>.

I have also removed the unwanted position for the CURRENCY SIGN (U+00A4) on the layer for Currency Signs.

**Comment by springcomp** [comment] 2024-01-13 16:03
@jbrianceau @dan-jac 

While updating the layout, I noticed a potential issue with the **COLON SIGN (U+20A1)** currency symbol.
It appears to be duplicated at two positions:

- <kbd>AltGr</kbd>+<kbd>¤</kbd>, <kbd>AltGr</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>
- <kbd>AltGr</kbd>+<kbd>¤</kbd>, <kbd>Shift</kbd>+<kbd>C</kbd>

This may be an error as it seems one of these should be the **CEDI SIGN (U+20B5)** currency sign `₵`.

What do you think?

**Comment by Slion** [comment] 2025-05-15 20:41
It looks like built-in support is now available in 24H2 according to: https://github.com/springcomp/optimized-azerty-win/issues/147#issuecomment-2884901854
